# Generated by Django 6.0.2 on 2026-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
