# Generated by Django 5.1.7 on 2026-03-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_successstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='company',
        ),
        migrations.AddField(
            model_name='alumni',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='job_status',
            field=models.CharField(blank=True, choices=[('Placed', 'Placed'), ('Promoted', 'Promoted'), ('Resigned', 'Resigned'), ('Higher Studies', 'Higher Studies')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='placement_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.department')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.programme'),
        ),
    ]
