# Generated by Django 5.1.7 on 2026-03-04 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_alumni_company_alumni_admission_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['-graduation_year', 'name'], 'verbose_name': 'Alumni', 'verbose_name_plural': 'Alumni Records'},
        ),
        migrations.AddField(
            model_name='alumni',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='mainapp.department'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='mainapp.programme'),
        ),
    ]
