# Generated by Django 5.1.7 on 2026-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_notification_notification_type_alter_alumni_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=150)),
                ('programme', models.CharField(blank=True, max_length=150, null=True)),
                ('graduation_year', models.PositiveIntegerField()),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('current_role', models.CharField(blank=True, max_length=200, null=True)),
                ('higher_studies', models.CharField(blank=True, max_length=200, null=True)),
                ('story_title', models.CharField(max_length=200)),
                ('journey', models.TextField()),
                ('college_experience', models.TextField(blank=True, null=True)),
                ('advice', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='alumni_journeys/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
