# Generated by Django 6.0.2 on 2026-04-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alumnijourney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniJourney',
        ),
    ]
