# Generated by Django 6.0.2 on 2026-04-30 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_delete_alumnijourney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessStory',
        ),
    ]
